create table room (
	room_id INT NOT NULL PRIMARY KEY,
	type VARCHAR(17) NOT NULL,
	status VARCHAR(13) NOT NULL
);
insert into room (room_id, type, status) values (1, 'General', 'Available');
insert into room (room_id, type, status) values (2, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (3, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (4, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (5, 'ICU', 'Not available');
insert into room (room_id, type, status) values (6, 'ICU', 'Not available');
insert into room (room_id, type, status) values (7, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (8, 'General', 'Available');
insert into room (room_id, type, status) values (9, 'General', 'Available');
insert into room (room_id, type, status) values (10, 'General', 'Available');
insert into room (room_id, type, status) values (11, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (12, 'General', 'Available');
insert into room (room_id, type, status) values (13, 'General', 'Available');
insert into room (room_id, type, status) values (14, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (15, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (16, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (17, 'ICU', 'Available');
insert into room (room_id, type, status) values (18, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (19, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (20, 'ICU', 'Not available');
insert into room (room_id, type, status) values (21, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (22, 'General', 'Not available');
insert into room (room_id, type, status) values (23, 'ICU', 'Not available');
insert into room (room_id, type, status) values (24, 'NICU', 'Not available');
insert into room (room_id, type, status) values (25, 'General', 'Available');
insert into room (room_id, type, status) values (26, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (27, 'NICU', 'Available');
insert into room (room_id, type, status) values (28, 'General', 'Available');
insert into room (room_id, type, status) values (29, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (30, 'ICU', 'Not available');
insert into room (room_id, type, status) values (31, 'General', 'Not available');
insert into room (room_id, type, status) values (32, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (33, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (34, 'ICU', 'Available');
insert into room (room_id, type, status) values (35, 'ICU', 'Not available');
insert into room (room_id, type, status) values (36, 'General', 'Not available');
insert into room (room_id, type, status) values (37, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (38, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (39, 'General', 'Not available');
insert into room (room_id, type, status) values (40, 'NICU', 'Not available');
insert into room (room_id, type, status) values (41, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (42, 'General', 'Available');
insert into room (room_id, type, status) values (43, 'General', 'Not available');
insert into room (room_id, type, status) values (44, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (45, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (46, 'General', 'Not available');
insert into room (room_id, type, status) values (47, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (48, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (49, 'General', 'Not available');
insert into room (room_id, type, status) values (50, 'General', 'Not available');
insert into room (room_id, type, status) values (51, 'General', 'Available');
insert into room (room_id, type, status) values (52, 'General', 'Not available');
insert into room (room_id, type, status) values (53, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (54, 'General', 'Not available');
insert into room (room_id, type, status) values (55, 'General', 'Available');
insert into room (room_id, type, status) values (56, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (57, 'General', 'Not available');
insert into room (room_id, type, status) values (58, 'NICU', 'Not available');
insert into room (room_id, type, status) values (59, 'ICU', 'Not available');
insert into room (room_id, type, status) values (60, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (61, 'ICU', 'Not available');
insert into room (room_id, type, status) values (62, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (63, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (64, 'NICU', 'Not available');
insert into room (room_id, type, status) values (65, 'NICU', 'Not available');
insert into room (room_id, type, status) values (66, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (67, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (68, 'ICU', 'Not available');
insert into room (room_id, type, status) values (69, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (70, 'General', 'Available');
insert into room (room_id, type, status) values (71, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (72, 'General', 'Not available');
insert into room (room_id, type, status) values (73, 'General', 'Not available');
insert into room (room_id, type, status) values (74, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (75, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (76, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (77, 'General', 'Not available');
insert into room (room_id, type, status) values (78, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (79, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (80, 'ICU', 'Not available');
insert into room (room_id, type, status) values (81, 'General', 'Not available');
insert into room (room_id, type, status) values (82, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (83, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (84, 'General', 'Not available');
insert into room (room_id, type, status) values (85, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (86, 'ICU', 'Available');
insert into room (room_id, type, status) values (87, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (88, 'General', 'Not available');
insert into room (room_id, type, status) values (89, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (90, 'General', 'Available');
insert into room (room_id, type, status) values (91, 'ICU', 'Not available');
insert into room (room_id, type, status) values (92, 'NICU', 'Not available');
insert into room (room_id, type, status) values (93, 'NICU', 'Available');
insert into room (room_id, type, status) values (94, 'General', 'Not available');
insert into room (room_id, type, status) values (95, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (96, 'General', 'Not available');
insert into room (room_id, type, status) values (97, 'General', 'Available');
insert into room (room_id, type, status) values (98, 'General', 'Not available');
insert into room (room_id, type, status) values (99, 'General', 'Not available');
insert into room (room_id, type, status) values (100, 'General', 'Not available');
insert into room (room_id, type, status) values (101, 'ICU', 'Available');
insert into room (room_id, type, status) values (102, 'General', 'Not available');
insert into room (room_id, type, status) values (103, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (104, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (105, 'General', 'Not available');
insert into room (room_id, type, status) values (106, 'General', 'Available');
insert into room (room_id, type, status) values (107, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (108, 'General', 'Not available');
insert into room (room_id, type, status) values (109, 'General', 'Not available');
insert into room (room_id, type, status) values (110, 'ICU', 'Not available');
insert into room (room_id, type, status) values (111, 'General', 'Not available');
insert into room (room_id, type, status) values (112, 'General', 'Available');
insert into room (room_id, type, status) values (113, 'ICU', 'Not available');
insert into room (room_id, type, status) values (114, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (115, 'General', 'Available');
insert into room (room_id, type, status) values (116, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (117, 'General', 'Not available');
insert into room (room_id, type, status) values (118, 'General', 'Not available');
insert into room (room_id, type, status) values (119, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (120, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (121, 'General', 'Available');
insert into room (room_id, type, status) values (122, 'ICU', 'Not available');
insert into room (room_id, type, status) values (123, 'ICU', 'Available');
insert into room (room_id, type, status) values (124, 'NICU', 'Available');
insert into room (room_id, type, status) values (125, 'General', 'Not available');
insert into room (room_id, type, status) values (126, 'General', 'Available');
insert into room (room_id, type, status) values (127, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (128, 'ICU', 'Not available');
insert into room (room_id, type, status) values (129, 'General', 'Not available');
insert into room (room_id, type, status) values (130, 'ICU', 'Not available');
insert into room (room_id, type, status) values (131, 'General', 'Not available');
insert into room (room_id, type, status) values (132, 'ICU', 'Available');
insert into room (room_id, type, status) values (133, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (134, 'General', 'Not available');
insert into room (room_id, type, status) values (135, 'ICU', 'Available');
insert into room (room_id, type, status) values (136, 'General', 'Not available');
insert into room (room_id, type, status) values (137, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (138, 'General', 'Available');
insert into room (room_id, type, status) values (139, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (140, 'General', 'Available');
insert into room (room_id, type, status) values (141, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (142, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (143, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (144, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (145, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (146, 'ICU', 'Not available');
insert into room (room_id, type, status) values (147, 'General', 'Available');
insert into room (room_id, type, status) values (148, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (149, 'General', 'Not available');
insert into room (room_id, type, status) values (150, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (151, 'General', 'Not available');
insert into room (room_id, type, status) values (152, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (153, 'ICU', 'Not available');
insert into room (room_id, type, status) values (154, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (155, 'ICU', 'Available');
insert into room (room_id, type, status) values (156, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (157, 'General', 'Available');
insert into room (room_id, type, status) values (158, 'General', 'Not available');
insert into room (room_id, type, status) values (159, 'General', 'Available');
insert into room (room_id, type, status) values (160, 'General', 'Not available');
insert into room (room_id, type, status) values (161, 'General', 'Available');
insert into room (room_id, type, status) values (162, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (163, 'General', 'Available');
insert into room (room_id, type, status) values (164, 'ICU', 'Available');
insert into room (room_id, type, status) values (165, 'General', 'Not available');
insert into room (room_id, type, status) values (166, 'General', 'Not available');
insert into room (room_id, type, status) values (167, 'General', 'Not available');
insert into room (room_id, type, status) values (168, 'General', 'Available');
insert into room (room_id, type, status) values (169, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (170, 'ICU', 'Available');
insert into room (room_id, type, status) values (171, 'ICU', 'Available');
insert into room (room_id, type, status) values (172, 'General', 'Not available');
insert into room (room_id, type, status) values (173, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (174, 'General', 'Available');
insert into room (room_id, type, status) values (175, 'General', 'Available');
insert into room (room_id, type, status) values (176, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (177, 'General', 'Not available');
insert into room (room_id, type, status) values (178, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (179, 'General', 'Available');
insert into room (room_id, type, status) values (180, 'ICU', 'Not available');
insert into room (room_id, type, status) values (181, 'General', 'Available');
insert into room (room_id, type, status) values (182, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (183, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (184, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (185, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (186, 'ICU', 'Not available');
insert into room (room_id, type, status) values (187, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (188, 'General', 'Not available');
insert into room (room_id, type, status) values (189, 'NICU', 'Not available');
insert into room (room_id, type, status) values (190, 'General', 'Not available');
insert into room (room_id, type, status) values (191, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (192, 'General', 'Available');
insert into room (room_id, type, status) values (193, 'NICU', 'Not available');
insert into room (room_id, type, status) values (194, 'General', 'Available');
insert into room (room_id, type, status) values (195, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (196, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (197, 'General', 'Available');
insert into room (room_id, type, status) values (198, 'General', 'Available');
insert into room (room_id, type, status) values (199, 'ICU', 'Not available');
insert into room (room_id, type, status) values (200, 'ICU', 'Not available');
insert into room (room_id, type, status) values (201, 'General', 'Not available');
insert into room (room_id, type, status) values (202, 'General', 'Available');
insert into room (room_id, type, status) values (203, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (204, 'General', 'Not available');
insert into room (room_id, type, status) values (205, 'NICU', 'Not available');
insert into room (room_id, type, status) values (206, 'ICU', 'Not available');
insert into room (room_id, type, status) values (207, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (208, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (209, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (210, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (211, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (212, 'General', 'Not available');
insert into room (room_id, type, status) values (213, 'General', 'Available');
insert into room (room_id, type, status) values (214, 'ICU', 'Not available');
insert into room (room_id, type, status) values (215, 'NICU', 'Available');
insert into room (room_id, type, status) values (216, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (217, 'General', 'Not available');
insert into room (room_id, type, status) values (218, 'General', 'Available');
insert into room (room_id, type, status) values (219, 'ICU', 'Available');
insert into room (room_id, type, status) values (220, 'General', 'Available');
insert into room (room_id, type, status) values (221, 'ICU', 'Not available');
insert into room (room_id, type, status) values (222, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (223, 'General', 'Available');
insert into room (room_id, type, status) values (224, 'ICU', 'Not available');
insert into room (room_id, type, status) values (225, 'General', 'Available');
insert into room (room_id, type, status) values (226, 'ICU', 'Not available');
insert into room (room_id, type, status) values (227, 'General', 'Not available');
insert into room (room_id, type, status) values (228, 'NICU', 'Not available');
insert into room (room_id, type, status) values (229, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (230, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (231, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (232, 'NICU', 'Available');
insert into room (room_id, type, status) values (233, 'General', 'Not available');
insert into room (room_id, type, status) values (234, 'General', 'Available');
insert into room (room_id, type, status) values (235, 'General', 'Not available');
insert into room (room_id, type, status) values (236, 'ICU', 'Not available');
insert into room (room_id, type, status) values (237, 'ICU', 'Not available');
insert into room (room_id, type, status) values (238, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (239, 'NICU', 'Not available');
insert into room (room_id, type, status) values (240, 'ICU', 'Available');
insert into room (room_id, type, status) values (241, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (242, 'ICU', 'Not available');
insert into room (room_id, type, status) values (243, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (244, 'General', 'Available');
insert into room (room_id, type, status) values (245, 'General', 'Available');
insert into room (room_id, type, status) values (246, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (247, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (248, 'General', 'Not available');
insert into room (room_id, type, status) values (249, 'ICU', 'Available');
insert into room (room_id, type, status) values (250, 'ICU', 'Not available');
insert into room (room_id, type, status) values (251, 'General', 'Not available');
insert into room (room_id, type, status) values (252, 'General', 'Not available');
insert into room (room_id, type, status) values (253, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (254, 'Deluxe', 'Available');
insert into room (room_id, type, status) values (255, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (256, 'General', 'Not available');
insert into room (room_id, type, status) values (257, 'General', 'Not available');
insert into room (room_id, type, status) values (258, 'General', 'Not available');
insert into room (room_id, type, status) values (259, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (260, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (261, 'General', 'Not available');
insert into room (room_id, type, status) values (262, 'General', 'Not available');
insert into room (room_id, type, status) values (263, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (264, 'General', 'Not available');
insert into room (room_id, type, status) values (265, 'NICU', 'Available');
insert into room (room_id, type, status) values (266, 'General', 'Available');
insert into room (room_id, type, status) values (267, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (268, 'General', 'Available');
insert into room (room_id, type, status) values (269, 'General', 'Not available');
insert into room (room_id, type, status) values (270, 'Deluxe', 'Not available');
insert into room (room_id, type, status) values (271, 'General', 'Not available');
insert into room (room_id, type, status) values (272, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (273, 'ICU', 'Not available');
insert into room (room_id, type, status) values (274, 'General', 'Not available');
insert into room (room_id, type, status) values (275, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (276, 'General', 'Not available');
insert into room (room_id, type, status) values (277, 'ICU', 'Not available');
insert into room (room_id, type, status) values (278, 'NICU', 'Available');
insert into room (room_id, type, status) values (279, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (280, 'NICU', 'Not available');
insert into room (room_id, type, status) values (281, 'General', 'Not available');
insert into room (room_id, type, status) values (282, 'General', 'Available');
insert into room (room_id, type, status) values (283, 'ICU', 'Not available');
insert into room (room_id, type, status) values (284, 'Twin Sharing Room', 'Available');
insert into room (room_id, type, status) values (285, 'General', 'Available');
insert into room (room_id, type, status) values (286, 'ICU', 'Available');
insert into room (room_id, type, status) values (287, 'General', 'Not available');
insert into room (room_id, type, status) values (288, 'General', 'Not available');
insert into room (room_id, type, status) values (289, 'General', 'Not available');
insert into room (room_id, type, status) values (290, 'General', 'Not available');
insert into room (room_id, type, status) values (291, 'General', 'Available');
insert into room (room_id, type, status) values (292, 'General', 'Not available');
insert into room (room_id, type, status) values (293, 'General', 'Not available');
insert into room (room_id, type, status) values (294, 'General', 'Not available');
insert into room (room_id, type, status) values (295, 'Twin Sharing Room', 'Not available');
insert into room (room_id, type, status) values (296, 'General', 'Not available');
insert into room (room_id, type, status) values (297, 'General', 'Not available');
insert into room (room_id, type, status) values (298, 'General', 'Not available');
insert into room (room_id, type, status) values (299, 'General', 'Not available');
insert into room (room_id, type, status) values (300, 'General', 'Not available');
